#!/usr/bin/env bash
# Open the iOS app in Xcode.
#
# The Xcode project is generated by Flutter and lives four levels down at
# packages/wh40k_app/ios/, so opening the repository root in Xcode shows
# nothing. Open the WORKSPACE, never Runner.xcodeproj.
#
# Also refreshes Flutter's generated Xcode config first. A stale
# Generated.xcconfig is the usual reason a build works from the terminal but
# fails inside Xcode.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP="$ROOT/packages/wh40k_app"

command -v flutter >/dev/null || {
  echo "flutter not on PATH — add /opt/homebrew/bin" >&2; exit 2; }

echo "refreshing Flutter's Xcode config..."
(cd "$APP" && flutter build ios --config-only >/dev/null)

echo "opening Runner.xcworkspace"
open "$APP/ios/Runner.xcworkspace"

cat <<'NOTE'

In Xcode:
  Scheme      Runner            (not FlutterFramework or the plugin package)
  Destination Any iOS Device    for Archive; a simulator for Run

Most of the time you do not need Xcode at all:
  cd packages/wh40k_app && flutter run
NOTE
